# Generated by Django 3.2.25 on 2024-05-12 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=20, verbose_name="Matricule de l'enseignant")),
                ('Nom', models.CharField(max_length=100, verbose_name="Nom de l'enseignant")),
                ('Prenom', models.CharField(max_length=100, verbose_name="Prenom de l'enseignant")),
                ('Lieu_de_naissance', models.DateTimeField(verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('Status', models.CharField(choices=[('P', 'Proviseur'), ('C', 'Censeur')], max_length=1)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10, verbose_name='Code de la salle')),
                ('Effectif', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCourse', models.PositiveIntegerField(verbose_name='Numéro de la leçon')),
                ('Titre', models.CharField(max_length=50, verbose_name='Titre de la leçon')),
                ('Nature', models.CharField(choices=[('Pratique', 'Pratique'), ('Theorique', 'Theorique'), ('Hybride', 'Hybride')], max_length=20, verbose_name='Nature de la leçon')),
                ('Duree', models.DurationField(blank=True, null=True, verbose_name='Durée de la leçon')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10, verbose_name='Code du département')),
                ('Intitule', models.CharField(max_length=20, verbose_name='Intitulé du Département')),
                ('Effectif', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=100, verbose_name='Objectif')),
            ],
        ),
        migrations.CreateModel(
            name='UA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumUA', models.PositiveIntegerField(verbose_name='Numéro du UA')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Objectifs', models.ManyToManyField(blank=True, null=True, to='Gestion.Objectif', verbose_name="Les objectifs de l'UA")),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumNiveau', models.PositiveIntegerField(verbose_name='Numéro du Niveau')),
                ('Cycle', models.CharField(choices=[('Observation', 'Observation'), ('Orientation', 'Orientation')], max_length=20, verbose_name='Cycle du Niveau')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumModule', models.PositiveIntegerField(default=0, verbose_name='Numéro du module')),
                ('Title', models.CharField(max_length=255, verbose_name='Intitulé du module')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeMatiere', models.CharField(max_length=10, verbose_name='Code de la Matiere')),
                ('Intitule', models.CharField(max_length=255, verbose_name='Intitulé de la Matiere')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KitDig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeK', models.CharField(max_length=10, verbose_name='Code du kit')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.administrateur', verbose_name="Administrateur qui l'a ajouté")),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumKit', models.PositiveIntegerField()),
                ('Nom', models.CharField(max_length=50, verbose_name="Nom de l'équipement")),
                ('Quantite', models.PositiveIntegerField(default=1, verbose_name='Qauntité')),
                ('date_publiee', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=20, verbose_name="Matricule de l'enseignant")),
                ('Nom', models.CharField(max_length=100, verbose_name="Nom de l'enseignant")),
                ('Prenom', models.CharField(max_length=100, verbose_name="Prenom de l'enseignant")),
                ('lieu_de_naissance', models.DateTimeField(verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.departement', verbose_name='Département associé')),
            ],
        ),
        migrations.CreateModel(
            name='DigCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100, verbose_name='Titre de la leçon digitalisée')),
                ('Debut', models.DateTimeField(auto_now=True)),
                ('Classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.classe', verbose_name='Classe du cours')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.course', verbose_name='Leçon à digitaliser')),
                ('Enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.enseignant', verbose_name='Enseignant qui dispense la leçon')),
                ('Kitdig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.kitdig', verbose_name="L'équipement utilisé")),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.niveau', verbose_name='Niveau de la leçon')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matiere', verbose_name='Matiere associée'),
        ),
        migrations.AddField(
            model_name='course',
            name='Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.module', verbose_name='Module associé'),
        ),
        migrations.AddField(
            model_name='course',
            name='Niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.niveau', verbose_name='Niveau associé'),
        ),
        migrations.AddField(
            model_name='course',
            name='Objectifs',
            field=models.ManyToManyField(blank=True, null=True, to='Gestion.Objectif', verbose_name="Les objectifs de l'UA"),
        ),
        migrations.AddField(
            model_name='course',
            name='UA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.ua', verbose_name='UA associée'),
        ),
    ]
