# Generated by Django 3.2.25 on 2024-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Objectifs',
            field=models.ManyToManyField(blank=True, to='Gestion.Objectif', verbose_name="Les objectifs de l'UA"),
        ),
        migrations.AlterField(
            model_name='ua',
            name='Objectifs',
            field=models.ManyToManyField(blank=True, to='Gestion.Objectif', verbose_name="Les objectifs de l'UA"),
        ),
    ]
